fwmod: rename TAR_TOOL variable

diff --git a/fwmod b/fwmod
--- a/fwmod
+++ b/fwmod
@@ -171,7 +171,7 @@ TICHKSUM_TOOL="tichksum"
 MAKEDEVS_TOOL="makedevs"
 DEBUGFS_TOOL="debugfs"
 EXTERNAL_TOOL="external"
-TAR_TOOL="tar"
+TAR_BBA_TOOL="tar"
 TAR_GNU_TOOL="tar-gnu"
 MD5SUM_TOOL="md5sum"
 BUSYBOX_TOOL="busybox"
@@ -186,7 +186,7 @@ FINDSQUASHFS="${TOOLS_DIR}/${FINDSQUASHFS_TOOL}"
 TICHKSUM="${TOOLS_DIR}/${TICHKSUM_TOOL}"
 MAKEDEVS="${TOOLS_DIR}/${MAKEDEVS_TOOL}"
 MAKEDEVS_FILE="${TOOLS_DIR}/device.table"
-TAR="${TOOLS_DIR}/${TAR_TOOL}"
+TAR_BBA="${TOOLS_DIR}/${TAR_BBA_TOOL}"
 TAR_GNU="${TOOLS_DIR}/${TAR_GNU_TOOL}"
 MD5SUM="${TOOLS_DIR}/${MD5SUM_TOOL}"
 BUSYBOX="${TOOLS_DIR}/${BUSYBOX_TOOL}"
@@ -392,7 +392,7 @@ else
 			error 1 "cannot clean up directory $COPY_FS_DIR")
 		mkdir -p "$COPY_FS_DIR" ||
 			error 1 "cannot create directory $COPY_FS_DIR"
-		sudo "$TAR" -C "$COPY_FS_DIR" -xf "$rootfs_archive" ||
+		sudo "$TAR_BBA" -C "$COPY_FS_DIR" -xf "$rootfs_archive" ||
 			error 1 "cannot unpack root file system"
 		echo -e "done.\n"
 	fi
@@ -795,7 +795,7 @@ if [ "$DO_MOD" -gt 0 ]; then
 	[ -n "$PV" ] && echo0 "preparing directory build/modified/"
 	mkdir -p "$MOD_DIR"
 	[ "$FREETZ_AVM_HAS_UDEV" == y ] || exclude_dev="--exclude=./filesystem/dev"
-	"$TAR_GNU" -c  --owner=0 --group=0 --numeric-owner  -C "$ORG_DIR" $exclude_dev  --exclude='*.log' . | ${PV:-cat} | "$TAR" -x -C "$MOD_DIR" || error 1 "tar failed"
+	"$TAR_GNU" -c  --owner=0 --group=0 --numeric-owner  -C "$ORG_DIR" $exclude_dev  --exclude='*.log' . | ${PV:-cat} | "$TAR_BBA" -x -C "$MOD_DIR" || error 1 "tar failed"
 
 	# Fix some permissions
 	chmod -R u+w "$FILESYSTEM_MOD_DIR"
@@ -1283,11 +1283,11 @@ if [ "$DO_MOD" -gt 0 ]; then
 		pkg_name=$(pkg_name "$pkg")
 
 		"$TAR_GNU" $(find "${PACKAGES_DIR}/${pkg}/" -maxdepth 1 -type f -name ".exclude*" -printf '--exclude-from=%p ') \
-		  -c  --owner=0 --group=0 --numeric-owner  -C "${PACKAGES_DIR}/${pkg}/root" . | "$TAR" -x -C "$FILESYSTEM_MOD_DIR" || error 1 "tar failed"
+		  -c  --owner=0 --group=0 --numeric-owner  -C "${PACKAGES_DIR}/${pkg}/root" . | "$TAR_BBA" -x -C "$FILESYSTEM_MOD_DIR" || error 1 "tar failed"
 
 		if [ -d "${PACKAGES_DIR}/${pkg}/${VARTAR_SUBDIR}" ]; then
 			"$TAR_GNU" -c  --owner=0 --group=0 --numeric-owner  -C "${PACKAGES_DIR}/${pkg}/${VARTAR_SUBDIR}" . | \
-			  "$TAR" -x -C ${VARTAR_MOD_DIR} || error 1 "tar failed"
+			  "$TAR_BBA" -x -C ${VARTAR_MOD_DIR} || error 1 "tar failed"
 		fi
 
 		[ -r "${PACKAGES_DIR}/${pkg}/.language" ] && \
@@ -1314,14 +1314,14 @@ if [ "$DO_MOD" -gt 0 ]; then
 		if [ -e "${ADDON_DIR}/${pkg}/etc/init.d/rc.${pkg_name}" ]; then
 			echo "NOTICE: addon '$pkg' is in old-style format (no language support)." 1>&2
 			"$TAR_GNU" -c  --owner=0 --group=0 --numeric-owner  -C "${ADDON_DIR}/${pkg}" . | \
-			  "$TAR" -x -C "$FILESYSTEM_MOD_DIR" || error 1 "tar failed"
+			  "$TAR_BBA" -x -C "$FILESYSTEM_MOD_DIR" || error 1 "tar failed"
 		elif [ "$(echo ${pkg^^}-corrupt | sed -r 's/([^.-_-]*).*/\LfLawed-\1-Addon/' | md5sum | sed 's/ .*//')" != "80d00cf16e1a48ec11801feed60a2be7" ]; then
-			"$TAR"  $(find "${ADDON_DIR}/${pkg}/" -maxdepth 1 -type f -name ".exclude*" -printf '--exclude-from=%p ') -c -C "${ADDON_DIR}/${pkg}/root" . | \
-			  "$TAR" -x -C "$FILESYSTEM_MOD_DIR" || error 1 "tar failed"
+			"$TAR_BBA"  $(find "${ADDON_DIR}/${pkg}/" -maxdepth 1 -type f -name ".exclude*" -printf '--exclude-from=%p ') -c -C "${ADDON_DIR}/${pkg}/root" . | \
+			  "$TAR_BBA" -x -C "$FILESYSTEM_MOD_DIR" || error 1 "tar failed"
 
 			if [ -d "${ADDON_DIR}/${pkg}/${VARTAR_SUBDIR}" ]; then
 				"$TAR_GNU" -c  --owner=0 --group=0 --numeric-owner  -C "${ADDON_DIR}/${pkg}/${VARTAR_SUBDIR}" . | \
-				  "$TAR" -x -C ${VARTAR_MOD_DIR} || error 1 "tar failed"
+				  "$TAR_BBA" -x -C ${VARTAR_MOD_DIR} || error 1 "tar failed"
 			fi
 
 			[ -r "${ADDON_DIR}/${pkg}/.language" ] && \
@@ -1930,7 +1930,7 @@ if [ "$DO_ZIP" -gt 0 ]; then
 	fi
 	echo0 "zipping root file system to $zip_name"
 	[ "$FREETZ_REPRODUCIBLE" == "y" ] && sync_timestamps "$FILESYSTEM_MOD_DIR" "$FILESYSTEM_DIR"
-	"$TAR" -C "$FILESYSTEM_MOD_DIR" -czf "$zip_name" .
+	"$TAR_BBA" -C "$FILESYSTEM_MOD_DIR" -czf "$zip_name" .
 	if [ $? -ne 0 ] || ! is_valid_tarball "$zip_name"; then
 		mv "${zip_name}" "${zip_name}.corrupted" 2>/dev/null
 		error 1 "zipping of root file system failed"
@@ -2203,7 +2203,7 @@ if [ "$action_names" ]; then
 		modexternal="${FW_IMAGES_DIR:-$DIR}/${modstring}.external"
 		echo "packing ${modexternal}"
 		[ "$FREETZ_REPRODUCIBLE" == "y" ] && sync_timestamps "$EXTERNAL_MOD_DIR"
-		"$TAR" -C "$EXTERNAL_MOD_DIR" -cf "$modexternal" .
+		"$TAR_BBA" -C "$EXTERNAL_MOD_DIR" -cf "$modexternal" .
 		if [ $? -ne 0 ] || ! is_valid_tarball "$modexternal"; then
 			mv "${modexternal}" "${modexternal}.corrupted" 2>/dev/null
 			error 1 "packing of external tar failed"
@@ -2217,7 +2217,7 @@ if [ "$action_names" ]; then
 				pkgexternal="${FW_IMAGES_DIR:-$DIR}/${modstring}_${pkg}.external"
 				echo "packing ${pkgexternal}"
 				[ "$FREETZ_REPRODUCIBLE" == "y" ] && sync_timestamps "$EXTERNAL_MOD_DIR-${pkg}"
-				"$TAR" -C "$EXTERNAL_MOD_DIR-${pkg}" -cf "$pkgexternal" .
+				"$TAR_BBA" -C "$EXTERNAL_MOD_DIR-${pkg}" -cf "$pkgexternal" .
 				if [ $? -ne 0 ] || ! is_valid_tarball "$pkgexternal"; then
 					mv "${pkgexternal}" "${pkgexternal}.corrupted" 2>/dev/null
 					error 1 "packing of external-$pkg tar failed"
