push firmware: PRODUCT does not exist for old fos

diff --git a/tools/push_firmware_experimental b/tools/push_firmware_experimental
--- a/tools/push_firmware_experimental
+++ b/tools/push_firmware_experimental
@@ -115,7 +115,7 @@ function push_fw() {
 	done
 	echo
 	[ -z "$env_ProductID" ] && echo "You are not connected to the bootloader of the device." && exit 1
-	[ "${PRODUCT% (*}" != "$env_ProductID" ] && echo "Error, ProductID of image does not match device" && exit 1
+	[ -n "$PRODUCT" ] && [ "${PRODUCT% (*}" != "$env_ProductID" ] && echo "Error, ProductID of image does not match device" && exit 1
 
 	if [ -n "$ISRAM$ISFIT" ]; then
 		if [ "${FULLSIZE//0/}" == "x" ]; then
