push firmware: remove read_enval

diff --git a/tools/push_firmware b/tools/push_firmware
--- a/tools/push_firmware
+++ b/tools/push_firmware
@@ -105,16 +105,6 @@ function get_device_params() {
 	ISWAITS=true
 }
 
-function read_enval() {
-	ftp -v -n <<EOT | sed -rn "s/^$1[ \t]*//p"
-open $ip
-user adam2 adam2
-quote GETENV $1
-quote BYE
-quit
-EOT
-}
-
 function push_fw() {
 	trap 'echo ; echo "aborted" ; exit 1' TERM INT
 
@@ -138,20 +128,13 @@ function push_fw() {
 		eval echo -e "\ \ \ $x:\ \ \ \ \ \\\t   \$env_$x"
 	done
 	echo
-
-	if [ "${PRODUCT% (*}" != "$env_ProductID" ]; then
-		echo "Error, ProductID of image does not match device"
-		exit 1
-	fi
-	exit
+	[ "${PRODUCT% (*}" != "$env_ProductID" ] && echo "Error, ProductID of image does not match device"&& exit 1
 
 	if [ -n "$ISRAM$ISFIT" ]; then
 		if [ "${FULLSIZE//0/}" == "x" ]; then
-			wait_loader
-			enval="$(read_enval memsize)"
-			[ "$enval" != "${enval#0x}" ] && FULLSIZE="$enval"
+			[ "$env_memsize" != "${env_memsize#0x}" ] && FULLSIZE="$env_memsize"
 			[ -z "$FULLSIZE" ] && echo "Invalid value for memsize." && exit 1
-			echo " * Detected memsize: '$enval'"
+			echo " * Detected memsize: '$env_memsize' (~$(($env_memsize/1024/1024)) MB)"
 			echo
 		fi
 
@@ -179,13 +162,11 @@ function push_fw() {
 
 	if [ ! $ISSINGLE ]; then
 		if [ ! $LFS ] || [ -n "$ISDUAL$ISUIMG" -a "$LFS" == "9" ]; then
-			wait_loader
-			enval="$(read_enval linux_fs_start)"
-			[ "$enval" != "0" -a "$enval" != "1" -a "$enval" != "" ] && echo "Invalid value for linux_fs_start." && exit 1
-			echo " * Detected linux_fs_start: '${enval:-<unset>}'"
-			[ -z "$enval" ] && enval=0 #factory
-			[ -z "$LFS" ]     && LFS="$(( ($enval + 1) % 2))" #other
-			[ "$LFS" == "9" ] && LFS="$enval" #current
+			[ "$env_linux_fs_start" != "0" -a "$env_linux_fs_start" != "1" -a "$env_linux_fs_start" != "" ] && echo "Invalid value for linux_fs_start." && exit 1
+			echo " * Detected linux_fs_start: '${env_linux_fs_start:-<unset>}'"
+			[ -z "$env_linux_fs_start" ] && env_linux_fs_start=0 #factory
+			[ -z "$LFS" ]     && LFS="$(( ($env_linux_fs_start + 1) % 2))" #other
+			[ "$LFS" == "9" ] && LFS="$env_linux_fs_start" #current
 			echo " * Designated linux_fs_start: $LFS"
 			echo
 		fi
