push firmware: read env for all devices

diff --git a/tools/push_firmware b/tools/push_firmware
--- a/tools/push_firmware
+++ b/tools/push_firmware
@@ -66,15 +66,15 @@ function wait_loader() {
 # Will not replace variables already valued.
 # Return 0 if success, else 1
 function read_env() {
-	echo "Reading 'env' file:"
 	tmpenv="$(mktemp -tu freetz_env_XXX)"
+	echo " * Reading 'env' file to $tmpenv"
 	echo "open $ip
 user adam2 adam2
 debug
 bin
 quote MEDIA SDRAM
 get env $tmpenv
-quit" | ftp -v -n -p &
+quit" | ftp -v -n -p 2>/dev/null 1>&2 &
 	bg_pid=$!
 
 	count=0  # give 10 seconds to read the file, detecting the ending line, then kill the FTP
@@ -84,34 +84,11 @@ quit" | ftp -v -n -p &
 	done
 	kill $bg_pid >/dev/null 2>&1  # this is needed as the FTP client freezes at the end of the file transfer
 	wait $bg_pid
-	test -f "$tmpenv" || return 1
-	env_file=$(<"$tmpenv")
+	grep -qs ^wlan_ssid "$tmpenv" && dos2unix -q "$tmpenv" || rm -f "$tmpenv"
+}
 
-	# All references must exist to continue
-	[[ "$env_file" == *"memsize "* ]] || return 1
-	[[ "$env_file" == *"linux_fs_start "* ]] || return 1
-	[[ "$env_file" == *"ProductID "* ]] || return 1
-	[[ "$env_file" == *"firstfreeaddress "* ]] || return 1
-
-	enval=$(echo "$env_file" | sed '/^memsize[\t ]/!d; s/^memsize[\t ]*//; s/\r//')
-	[ -z "$enval" ] && echo "Invalid value for memsize." && return 1
-	[ -z "$FULLSIZE" ] && [ "$enval" != "${enval#0x}" ] && FULLSIZE="$enval"
-
-	enval=$(echo "$env_file" | sed '/^linux_fs_start[\t ]/!d; s/^linux_fs_start[\t ]*//; s/\r//')
-	[ "$enval" != "0" -a "$enval" != "1" ] && echo "Invalid value for linux_fs_start." && return 1
-	CURRENT_LFS="$enval"
-	[ -z "$LFS" ] && LFS="$(( ($enval + 1) % 2))" #other
-	[ "$LFS" == "9" ] && LFS="$enval" #current
-
-	enval=$(echo "$env_file" | sed '/^ProductID[\t ]/!d; s/^ProductID[\t ]*//; s/\r//')
-	[ -z "$enval" ] && echo "Invalid value for ProductID." && return 1
-	[ -z "$ProductID" ] && ProductID="$enval"
-
-	enval=$(echo "$env_file" | sed '/^firstfreeaddress[\t ]/!d; s/^firstfreeaddress[\t ]*//; s/\r//')
-	[ -z "$enval" ] && echo "Invalid value for firstfreeaddress." && return 1
-	[ -z "$MAPSTART" ] && [ "$enval" != "${enval#0x}" ] && MAPSTART="$enval"
-	echo -e "'env' file downloaded with valid values.\n"
-	return 0
+function read_env_val() {
+	sed -n "s/^$1[ \t]*[ \t]//p" "$tmpenv" 2>/dev/null
 }
 
 function get_device_params() {
@@ -153,6 +130,20 @@ function push_fw() {
 		done
 	fi
 	echo
+
+	wait_loader
+	read_env
+	for x in ProductID SerialNumber HWRevision HWSubRevision memsize linux_fs_start; do
+		eval env_$x="\$(read_env_val '$x')"
+		eval echo -e "\ \ \ $x:\ \ \ \ \ \\\t   \$env_$x"
+	done
+	echo
+
+	if [ "${PRODUCT% (*}" != "$env_ProductID" ]; then
+		echo "Error, ProductID of image does not match device"
+		exit 1
+	fi
+	exit
 
 	if [ -n "$ISRAM$ISFIT" ]; then
 		if [ "${FULLSIZE//0/}" == "x" ]; then
