actions: update make_freetz

diff --git a/.github/workflows/make_freetz.yml b/.github/workflows/make_freetz.yml
--- a/.github/workflows/make_freetz.yml
+++ b/.github/workflows/make_freetz.yml
@@ -6,7 +6,7 @@ on:
     paths:
       - '.github/workflows/make_freetz.yml'
   schedule:
-    - cron: '00 16 * * 0'
+    - cron: '00 16 * * 1'
   workflow_dispatch:
 
 jobs:
@@ -15,8 +15,15 @@ jobs:
 #     image: ubuntu:20.04
 #     image: freetzng/firmware
       image: ghcr.io/freetz-ng/firmware
+#   strategy:
+#     fail-fast: false
+#     matrix:
+#       fritz: [ 4040,     4060,5530,5590,5690_PRO,6591,6660,     6690,6850_V1,6850_V2,7510,7520_V1,        7530_W5,7530_W6_V1,7583_V1,7583_V2,7590_W5,7590_W6,     7690,GATE ]
+#       fritz: [ 4040,4050,4060,5530,5590,5690_PRO,6591,6660,6670,6690,6850_V1,6850_V2,7510,7520_V1,7520_V2,7530_W5,7530_W6_V1,7583_V1,7583_V2,7590_W5,7590_W6,7682,7690,GATE ]
     runs-on: ubuntu-latest
 
+    env:
+      CACHE_KEY: "${{ github.workflow }}"
     steps:
 
 #     - name: update
@@ -50,19 +57,26 @@ jobs:
           path: |
             dl/*
             !dl/fw/*
-          key: ${{ github.workflow }}
+          key: ${{ env.CACHE_KEY }}
 
       - name: config
         run: |
           truncate -s0 .config
-          for x in  TYPE_7490 TYPE_FIRMWARE_07_2X TYPE_FIRMWARE_DETECT_LATEST; do echo "FREETZ_$x=y"  >> .config; done
-          for x in  PACKAGE_LDD PACKAGE_STRACE                               ; do echo "FREETZ_$x=y"  >> .config; done
-          for x in  PACKAGE_DROPBEAR                              ; do echo "# FREETZ_$x is not set"  >> .config; done
+          for x in  ftdi_sio  usbserial                               ; do echo "FREETZ_MODULE_$x=y"  >> .config; done
+          for x in  DROPBEAR                              ; do echo "# FREETZ_PACKAGE_$x is not set"  >> .config; done
+          for x in  LDD                                              ; do echo "FREETZ_PACKAGE_$x=y"  >> .config; done
+          for x in  COMPRESSED  UNCOMPRESSED                        ; do echo "FREETZ_SIZEINFO_$x=y"  >> .config; done
           echo '# FREETZ_TOOLCHAIN_CCACHE is not set'                                                 >> .config
-          echo 'FREETZ_USER_LEVEL_EXPERT=y'                                                           >> .config
+          echo 'FREETZ_VERBOSITY_FWMOD_2=y'                                                           >> .config
           echo 'FREETZ_VERBOSITY_LEVEL_0=y'                                                           >> .config
+          echo 'FREETZ_VERBOSITY_LEVEL=0'                                                             >> .config
+          echo 'FREETZ_USER_LEVEL_DEVELOPER=y'                                                        >> .config
           echo 'FREETZ_DL_SITE_USER="https://raw.githubusercontent.com/Freetz-NG/dl-mirror/master"'   >> .config
+          echo 'FREETZ_REAL_DEVELOPER_ONLY__DLURL="${{ secrets.ACTIONS_DLTCS }}"                      >> .config
+          echo 'FREETZ_DOWNLOAD_TOOLCHAIN=y'                                                          >> .config
+          echo 'FREETZ_HOSTTOOLS_DOWNLOAD=y'                                                          >> .config
           wget -q "${{ secrets.ACTIONS_CUSTOM }}cfg" -O cfg 2>/dev/null && mv cfg .config || rm -f cfg
+          grep -q '^FREETZ_TYPE_' .config || echo 'FREETZ_TYPE_7530_W6_V1=y'                          >> .config
           echo "################################################################" && du .config && wc -l .config
 
       - name: addon
@@ -103,38 +117,37 @@ jobs:
           echo "NAME=$NAME"
           test -n "$NAME"
 
-      - name: cleanup
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          ACTIONS_NAME: ${{ steps.vars.outputs.name }}
-        run: |
-          git config --global --add safe.directory $GITHUB_WORKSPACE
-          git config --local credential.helper '!x() { echo "password=$GITHUB_TOKEN"; };x'
-          git tag -d $ACTIONS_NAME && git push --delete origin $ACTIONS_NAME || true
-
-      - name: release
-        uses: ncipollo/release-action@v1
-        with:
-          tag: ${{ steps.vars.outputs.name }}
-          name: ${{ steps.vars.outputs.name }}
-          body: |
-            ${{ steps.vars.outputs.last }}
-            ${{ steps.vars.outputs.link }}
-          prerelease: false
-          allowUpdates: true
-          removeArtifacts: false
-          artifacts: "images/*"
-          token: ${{ secrets.GITHUB_TOKEN }}
-          replacesArtifacts: false
-          artifactErrorsFailBuild: true
-          draft: true
+#     - name: cleanup
+#       env:
+#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#         ACTIONS_NAME: ${{ steps.vars.outputs.name }}
+#       run: |
+#         git config --global --add safe.directory $GITHUB_WORKSPACE
+#         git config --local credential.helper '!x() { echo "password=$GITHUB_TOKEN"; };x'
+#         git tag -d $ACTIONS_NAME && git push --delete origin $ACTIONS_NAME || true
+#     - name: release
+#       uses: ncipollo/release-action@v1
+#       with:
+#         tag: ${{ steps.vars.outputs.name }}
+#         name: ${{ steps.vars.outputs.name }}
+#         body: |
+#           ${{ steps.vars.outputs.last }}
+#           ${{ steps.vars.outputs.link }}
+#         prerelease: false
+#         allowUpdates: true
+#         removeArtifacts: false
+#         artifacts: "images/*"
+#         token: ${{ secrets.GITHUB_TOKEN }}
+#         replacesArtifacts: false
+#         artifactErrorsFailBuild: true
+#         draft: true
 
       - name: cache_clear
         env:
           ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
         run: |
           ASSETS="$(curl -s  -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer $ACTIONS_TOKEN"  -H "X-GitHub-Api-Version: 2022-11-28"  "https://api.github.com/repos/${{ github.repository }}/actions/caches")"
-          ASSID="$(echo "$ASSETS" | grep -B7 "\"key\": *\"${{ github.workflow }}\"" | sed -rn 's/ *"id": *([^,]*),*/\1/p')"
+          ASSID="$(echo "$ASSETS" | grep -B7 "\"key\": *\"${{ env.CACHE_KEY }}\"" | sed -rn 's/ *"id": *([^,]*),*/\1/p')"
           curl -sL -X DELETE -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer $ACTIONS_TOKEN"  -H "X-GitHub-Api-Version: 2022-11-28"  "https://api.github.com/repos/${{ github.repository }}/actions/caches/$ASSID" && echo "Deleted ASSID=$ASSID ..." || true
       - name: cache_save
         uses: actions/cache/save@v4
@@ -143,6 +156,6 @@ jobs:
           path: |
             dl/*
             !dl/fw/*
-          key: ${{ github.workflow }}
+          key: ${{ env.CACHE_KEY }}
 
 
